sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t deb-sam/docker-complex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true deb-sam/docker-complex npm  test

after_success:
  - docker build -t debsam2019/complex-client ./client
  - docker build -t debsam2019/complex-nginx ./nginx
  - docker build -t debsam2019/complex-server ./server
  - docker build -t debsam2019/complex-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push debsam2019/complex-client
  - docker push debsam2019/complex-nginx
  - docker push debsam2019/complex-server
  - docker push debsam2019/complex-worker